[package]
name = "ghdbscan-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ndarray.workspace = true
rayon.workspace = true
ordered-float.workspace = true
kiddo = "4.2"
thiserror = "1.0"
rand = "0.8"
nalgebra = "0.32"

[dev-dependencies]
approx = "0.5"
